HRProject.UI/Areas/CompanyManager/Controllers/PermissionController.cs
using AutoMapper;
using HRProject.Entities.Entities;
using HRProject.Entities.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Security.Claims;
using System.Text;

namespace HRProject.UI.Areas.CompanyManager.Controllers
{
    [Area("CompanyManager"), Authorize(Roles = "CompanyManager")]
    public class PermissionController : Controller
    {
        string baseURL = "https://localhost:7127";
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment environment;

        public PermissionController(IMapper mapper, IWebHostEnvironment environment)
        {
            _mapper = mapper;
            this.environment = environment;
        }

        [HttpGet]
        public async Task<IActionResult> GetPermissionRequest()
        {
            var currentUser = HttpContext.User.Identity as ClaimsIdentity;
            var loginIdClaim = currentUser.FindFirst("ID");

            CompanyManagerEntity companyManagers = new CompanyManagerEntity();

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/CompanyManager/GetCompanyManagerById/{loginIdClaim.Value}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    companyManagers = JsonConvert.DeserializeObject<List<CompanyManagerEntity>>(apiCevap)[0];
                }
            }

            List<EmployeePermission> permissions=new List<EmployeePermission>();
            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Permission/GetPermissionRequestbyCompanyId/{companyManagers.CompanyId}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    permissions = JsonConvert.DeserializeObject<List<EmployeePermission>>(apiCevap);
                }
            }
            return View(permissions);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmedPermission(int id)
        {
            using(var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Permission/ConfirmedPermission/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetPermissionRequest");
        }
        [HttpGet]
        public async Task<IActionResult> CancelledPermission(int id)
        {
            EmployeePermission employeePermissions = new EmployeePermission();
            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Permission/GetEmployeePermissionbyId/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    employeePermissions = JsonConvert.DeserializeObject<EmployeePermission>(apiCevap);
                }
            }

            Employee employee = new Employee();
            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Employee/GetEmployeebyId/{employeePermissions.EmployeeId}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    employee = JsonConvert.DeserializeObject<List<Employee>>(apiCevap)[0];
                }
            }

            DateTime startDate = employeePermissions.StartDate.Value;
            DateTime endDate = employeePermissions.EndDate.Value;
            int differenceInDays = (int)(endDate - startDate).TotalDays;
            employee.AnnualDay += differenceInDays;

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employee), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync($"{baseURL}/api/Employee/UpdateAnnualDay/{employee.ID}", content))
                {
                    {
                        string apiCevap = await response.Content.ReadAsStringAsync();
                    }
                }
            }

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Permission/CancelledPermission/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetPermissionRequest");
        }
    }
}

HRProject.UI/Areas/CompanyManager/Views/Permission/GetPermissionRequest.cshtml
@{
    ViewData["Title"] = "GetPermissionRequest";
    Layout = "~/Areas/CompanyManager/Views/Shared/_LayoutCompanyManager.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>

@model List<EmployeePermission>


<div class="col-lg-12">
    <div class="card mx-4">
        <div class="card-header">
            <div class="align-items-lg-end">
                <strong class="card-title d-flex justify-content-center">Permission Request</strong>
            </div>
        </div>
        <div class="card-body">
            <div class="custom-tab">
                <nav>

                 
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <button type="button"
                                    class="nav-link active"
                                    role="tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#custom-nav-pending"
                                    aria-controls="custom-nav-pending"
                                    aria-selected="true">
                                Pending
                            </button>
                        </li>
                        <li class="nav-item">
                            <button type="button"
                                    class="nav-link"
                                    role="tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#custom-nav-confirmed"
                                    aria-controls="navs-top-profile"
                                    aria-selected="false">
                                Confirmed
                            </button>
                        </li>
                        <li class="nav-item">
                            <button type="button"
                                    class="nav-link"
                                    role="tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#custom-nav-cancelled"
                                    aria-controls="navs-top-messages"
                                    aria-selected="false">
                                Cancelled
                            </button>
                        </li>
                    </ul>

                </nav>
                <div class="tab-content pl-3 pt-2" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="custom-nav-pending" role="tabpanel" aria-labelledby="custom-nav-pending-permissions">
                        <div class="card">
                            <div class="card-header"></div>

                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Employee Fullname</th>
                                            <th>Permission Name</th>
                                            <th>Required Date</th>
                                            <th>Start Day of Permission Request</th>
                                            <th>End Day of Permission Request</th>
                                            <th>Operation</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @{
                                            int rowcountt = 1;
                                        }
                                        @foreach (EmployeePermission item in Model)
                                        {
                                            if (item.PermissionState == Status.Pending)
                                            {
                                                <tr>
                                                    <th scope="row">@rowcountt</th>
                                                    <td>@item.Employee.FirstName @item.Employee.LastName</td>
                                                    <td>@item.Permission.PermissionName</td>
                                                    <td>@item.RequiredDate</td>
                                                    <td>@item.StartDate.Value.ToShortDateString()</td>
                                                    <td>@item.EndDate.Value.ToShortDateString()</td>
                                                    <td>
                                                        
                                                        <a asp-area="CompanyManager" asp-controller="Permission" asp-action="ConfirmedPermission" asp-route-id="@item.ID" class="btn btn-sm btn-success">Confirmed</a>
                                                        <a asp-area="CompanyManager" asp-controller="Permission" asp-action="CancelledPermission" asp-route-id="@item.ID" class="btn btn-sm btn-danger">Cancelled</a>

                                                    </td>
                                                </tr>
                                            }

                                            rowcountt++;
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade show" id="custom-nav-confirmed" role="tabpanel" aria-labelledby="custom-nav-confirmed-permissions">
                        <div class="card">
                            <div class="card-header"> </div>

                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Employee Fullname</th>
                                            <th>Permission Name</th>
                                            <th>Required Date</th>
                                            <th>Start day of permission request</th>
                                            <th>End day of permission request</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @{
                                            int rowcount2 = 1;
                                        }
                                        @foreach (EmployeePermission item in Model)
                                        {
                                            if (item.PermissionState == Status.Confirmed)
                                            {
                                                <tr>
                                                    <th scope="row">@rowcountt</th>
                                                    <td>@item.Employee.FirstName @item.Employee.LastName</td>
                                                    <td>@item.Permission.PermissionName</td>
                                                    <td>@item.RequiredDate</td>
                                                    <td>@item.StartDate.Value.ToShortDateString()</td>
                                                    <td>@item.EndDate.Value.ToShortDateString()</td>
                                                </tr>
                                            }

                                            rowcount2++;
                                        }


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade show" id="custom-nav-cancelled" role="tabpanel" aria-labelledby="custom-nav-cancelled-permissions">
                        <div class="card">
                            <div class="card-header"> </div>


                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Employee Fullname</th>
                                            <th>Permission Name</th>
                                            <th>Required Date</th>
                                            <th>Start day of permission request</th>
                                            <th>End day of permission request</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @{
                                            int rowcount3 = 1;
                                        }
                                        @foreach (EmployeePermission item in Model)
                                        {
                                            if (item.PermissionState == Status.Canceled)
                                            {
                                                <tr>
                                                    <th scope="row">@rowcount3</th>
                                                    <td>@item.Employee.FirstName @item.Employee.LastName</td>
                                                    <td>@item.Permission.PermissionName</td>
                                                    <td>@item.RequiredDate</td>
                                                    <td>@item.StartDate.Value.ToShortDateString()</td>
                                                    <td>@item.EndDate.Value.ToShortDateString()</td>
                                                </tr>
                                            }

                                            rowcount3++;
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>