HRProject.UI/Areas/CompanyManager/Controllers/ExpenseController.cs
using AutoMapper;
using HRProject.Entities.Entities;
using HRProject.Entities.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace HRProject.UI.Areas.CompanyManager.Controllers
{
    [Area("CompanyManager"), Authorize(Roles = "CompanyManager")]
    public class ExpenseController : Controller
    {
        string baseURL = "https://localhost:7127";
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment environment;

        public ExpenseController(IMapper mapper, IWebHostEnvironment environment)
        {
            _mapper = mapper;
            this.environment = environment;
        }

        [HttpGet]
        public async Task<IActionResult> GetExpenseRequest()
        {
            var currentUser = HttpContext.User.Identity as ClaimsIdentity;
            var loginIdClaim = currentUser.FindFirst("ID");

            CompanyManagerEntity companyManagers = new CompanyManagerEntity();

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/CompanyManager/GetCompanyManagerById/{loginIdClaim.Value}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    companyManagers = JsonConvert.DeserializeObject<List<CompanyManagerEntity>>(apiCevap)[0];
                }
            }

            List<Expense> expenses = new List<Expense>();
            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Expense/GetExpenseRequestbyCompanyId/{companyManagers.CompanyId}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    expenses = JsonConvert.DeserializeObject<List<Expense>>(apiCevap);
                }
            }
            return View(expenses);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmedExpense(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Expense/ConfirmedExpense/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetExpenseRequest");
        }
        [HttpGet]
        public async Task<IActionResult> CancelledExpense(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/Expense/CancelledExpense/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetExpenseRequest");
        }
    }
}

HRProject.UI/Areas/CompanyManager/Views/Expense/GetExpenseRequest.cshtml
@{
    ViewData["Title"] = "GetExpense";
    Layout = "~/Areas/CompanyManager/Views/Shared/_LayoutCompanyManager.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>

@model List<Expense>


<div class="col-lg-12">
    <div class="card mx-4">
        <div class="card-header">
            <div class="align-items-lg-end">
                <strong class="card-title d-flex justify-content-center">Advance Payment Request</strong>
            </div>
        </div>
        <div class="card-body">
            <div class="custom-tab">
                <nav>


                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <button type="button"
                                    class="nav-link active"
                                    role="tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#custom-nav-pending"
                                    aria-controls="custom-nav-pending"
                                    aria-selected="true">
                                Pending
                            </button>
                        </li>
                        <li class="nav-item">
                            <button type="button"
                                    class="nav-link"
                                    role="tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#custom-nav-confirmed"
                                    aria-controls="navs-top-profile"
                                    aria-selected="false">
                                Confirmed
                            </button>
                        </li>
                        <li class="nav-item">
                            <button type="button"
                                    class="nav-link"
                                    role="tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#custom-nav-cancelled"
                                    aria-controls="navs-top-messages"
                                    aria-selected="false">
                                Cancelled
                            </button>
                        </li>
                    </ul>

                </nav>
                <div class="tab-content pl-3 pt-2" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="custom-nav-pending" role="tabpanel" aria-labelledby="custom-nav-pending-permissions">
                        <div class="card">
                            <div class="card-header"></div>

                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Employee Fullname</th>
                                            <th>Expense Name</th>
                                            <th>Request Date</th>
                                            <th>Currency</th>
                                            <th>Amount</th>
                                            <th>Attachment</th>
                                            <th>Operation</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (Expense item in Model)
                                        {
                                            if (item.ApprovalStatus == Status.Pending)
                                            {
                                                <tr>
                                                    <td>@item.Employee.FirstName @item.Employee.LastName</td>
                                                    <td>@item.ExpenseType.Value</td>
                                                    <td>@item.RequestDate</td>
                                                    <td>@item.Currency</td>
                                                    <td>@item.Amount</td>
                                                    <td>
                                                        <a target="_blank" href="@item.FileURL"><i class='bx bxs-file-pdf'></i></a>
                                                    </td>
                                                    <td>

                                                        <a asp-area="CompanyManager" asp-controller="Expense" asp-action="ConfirmedExpense" asp-route-id="@item.ID" class="btn btn-sm btn-success">Confirmed</a>
                                                        <a asp-area="CompanyManager" asp-controller="Expense" asp-action="CancelledExpense" asp-route-id="@item.ID" class="btn btn-sm btn-danger">Cancelled</a>

                                                    </td>
                                                </tr>
                                            }
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade show" id="custom-nav-confirmed" role="tabpanel" aria-labelledby="custom-nav-confirmed-permissions">
                        <div class="card">
                            <div class="card-header"> </div>

                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Employee Fullname</th>
                                            <th>Expense Name</th>
                                            <th>Request Date</th>
                                            <th>Currency</th>
                                            <th>Amount</th>
                                            <th>Attachment</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (Expense item in Model)
                                        {
                                            if (item.ApprovalStatus == Status.Confirmed)
                                            {
                                                <tr>
                                                    <td>@item.Employee.FirstName @item.Employee.LastName</td>
                                                    <td>@item.ExpenseType.Value</td>
                                                    <td>@item.RequestDate</td>
                                                    <td>@item.Currency</td>
                                                    <td>@item.Amount</td>
                                                    <td>
                                                        <a target="_blank" href="@item.FileURL"><i class='bx bxs-file-pdf'></i></a>
                                                    </td>
                                                </tr>
                                            }
                                        }


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade show" id="custom-nav-cancelled" role="tabpanel" aria-labelledby="custom-nav-cancelled-permissions">
                        <div class="card">
                            <div class="card-header"> </div>


                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Employee Fullname</th>
                                            <th>Expense Name</th>
                                            <th>Request Date</th>
                                            <th>Currency</th>
                                            <th>Amount</th>
                                            <th>Attachment</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (Expense item in Model)
                                        {
                                            if (item.ApprovalStatus == Status.Canceled)
                                            {
                                                <tr>
                                                    <td>@item.Employee.FirstName @item.Employee.LastName</td>
                                                    <td>@item.ExpenseType.Value</td>
                                                    <td>@item.RequestDate</td>
                                                    <td>@item.Currency</td>
                                                    <td>@item.Amount</td>
                                                    <td>
                                                        <a target="_blank" href="@item.FileURL"><i class='bx bxs-file-pdf'></i></a>
                                                    </td>
                                                </tr>
                                            }

                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>